import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import axios from '../lib/axios';
import type { PriceTagLink } from '../types';

// Admin-curated 5-album rail on the home page. Mirrors the mydig
// wall's data shape (album object per slot) minus the user_id —
// single global rail, not per-user. GET is public; PUT bulk-replace
// is admin-only and falls through to a 401 / 403 if the request
// arrives without an admin session.

export interface HomeFeatureAlbum {
  mbid: string;
  slug: string | null;
  title: string;
  artist: string;
  // Korean transliteration of artist + title — generated by the
  // pronunciation Claude pass (see services/claude.ts). Surfaces on
  // the home wall's price tag so the curated rail reads as a Korean
  // crate-digger's handwritten labels rather than untranslated
  // imports. Nullable: null on freshly registered albums whose
  // pronunciation backfill hasn't run yet — sticker falls back to
  // the original English string in that case.
  artistKo?: string | null;
  titleKo?: string | null;
  coverArtUrl: string | null;
  coverArtFallbacks?: string[];
  coverDominantColor?: string | null;
  spotifyUrl?: string | null;
  releaseDate?: string | null;
  // Aggregated review score (0-100, integer) and the number of
  // *scored* reviews behind it. Powers the dig.haus PICK sticker
  // gate on the home wall — show only when averageScore is at the
  // pick threshold AND reviewCount clears MIN_SCORED_FOR_AVG so a
  // single high-scoring review can't promote an album.
  averageScore?: number | null;
  reviewCount?: number;
  // Top purchase-link sticker (≤1 entry). Server picks soldout-last,
  // then ascending KRW; empty array when no purchase links registered.
  priceTagLinks?: PriceTagLink[];
}

export interface HomeFeatureItem {
  position: number;
  /** Per-slot note set explicitly by admin on `home_features.note`.
   *  Takes precedence over `adminReview` when both exist — the
   *  hero-context override path. */
  note: string | null;
  /** Admin's 50자 평 (`user_reviews.body` where author.is_admin = 1)
   *  for this album, if any. Used as the fallback post-it text when
   *  `note` is empty so the operator's voice on the album page
   *  automatically extends to the hero wall without a second
   *  authoring step. */
  adminReview: string | null;
  album: HomeFeatureAlbum;
}

// One slide in the carousel — its own backdrop + ink palette + 15
// LP slots. Server returns walls in `position ASC` order; the client
// renders them as parallel curatorial tracks (이번 주 발굴 / 시즌 무드
// / etc.) the visitor swipes between. Per-wall HERO_THEME tokens
// (inkColor / shadowCss / wallColor) replace the previous singleton
// from heroTheme.ts so basement5 (light surface) gets dark ink while
// basement_purple (dark surface) keeps cream.
export interface HomeWall {
  id: number;
  position: number;
  backdropFile: string;
  theme: string | null;
  description: string | null;
  inkColor: string;
  shadowCss: string;
  wallColor: string;
  // Handwritten header position knobs — px offsets from the wall's
  // top-left, rotation in degrees. Server fills defaults when the
  // columns are null, so these are always numbers in the payload.
  headerTopPx: number;
  headerLeftPx: number;
  headerRotationDeg: number;
  // Plastic-wrap raster overlay tuning — scale_pct = how much larger
  // than the cover (15 = 15% larger), offsets in px. blend_mode
  // controls how the texture composites onto the cover.
  plasticScalePct: number;
  plasticOffsetXPx: number;
  plasticOffsetYPx: number;
  plasticBlendMode: string;
  // Hero LP / title tuner — values in source-image px (the 2976×1500
  // backdrop coord space).
  lpSize: number;
  lpGap: number;
  upperLpXStart: number;
  lowerLpXStart: number;
  upperLpY: number;
  lowerLpY: number;
  titleFontSize: number;
  titleRotationDeg: number;
  items: HomeFeatureItem[];
}

export function useHomeFeatures() {
  return useQuery<{ walls: HomeWall[] }>({
    queryKey: ['home-features'],
    queryFn: async () => {
      const { data } = await axios.get('/api/home/features');
      return data;
    },
    staleTime: 30_000,
  });
}

// Each field is optional — the server treats missing keys as
// "don't touch", so the editor can PATCH only what changed.
export interface HomeMetaPatch {
  theme?: string | null;
  description?: string | null;
  headerTopPx?: number;
  headerLeftPx?: number;
  headerRotationDeg?: number;
  plasticScalePct?: number;
  plasticOffsetXPx?: number;
  plasticOffsetYPx?: number;
  plasticBlendMode?: string;
  lpSize?: number;
  lpGap?: number;
  upperLpXStart?: number;
  lowerLpXStart?: number;
  upperLpY?: number;
  lowerLpY?: number;
  titleFontSize?: number;
  titleRotationDeg?: number;
}

export function useUpdateHomeMeta(wallId: number = 1) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (meta: HomeMetaPatch) => {
      const { data } = await axios.patch(
        `/api/home/meta?wallId=${wallId}`,
        meta
      );
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['home-features'] });
    },
  });
}

export interface HomeFeatureItemPut {
  position: number;
  mbid: string;
  note?: string | null;
}

// Admin-only: swap one wall's position with its immediate left/right
// neighbour. The carousel is sorted by `position ASC`, so a successful
// swap re-orders which slide the visitor sees first / second / third.
export function useMoveHomeWall() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, dir }: { id: number; dir: 'left' | 'right' }) => {
      const { data } = await axios.post(
        `/api/home/walls/${id}/move?dir=${dir}`
      );
      return data as { ok: boolean; moved: boolean; newPosition?: number };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['home-features'] });
    },
  });
}

export function useReplaceHomeFeatures(wallId: number = 1) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (items: HomeFeatureItemPut[]) => {
      const { data } = await axios.put(
        `/api/home/features/items?wallId=${wallId}`,
        { items }
      );
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['home-features'] });
    },
  });
}
